apiVersion: v1
kind: PersistentVolume
metadata:
  name: ddclient
spec:
  capacity:
    storage: 10Mi
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.3
    path: /var/nfs/ddclient
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ddclient
spec:
  volumeName: ddclient
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Mi
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ddclient
  labels:
    app: ddclient
spec:
  schedule: "0 0 * * 0"
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: ddclient
    spec:
      backoffLimit: 3
      activeDeadlineSeconds: 60
      template:
        spec:
          containers:
            - name: ddclient
              image: linuxserver/ddclient
              imagePullPolicy: Always
              resources:
                requests:
                  memory: 128Mi
                  cpu: 100m
                limits:
                  memory: 256Mi
                  cpu: 200m
              env:
                - name: PUID
                  value: "1000"
                - name: PUID
                  value: "1000"
                - name: TZ
                  value: "America/Los_Angeles"
              volumeMounts:
                - name: ddclient
                  mountPath: /config
          restartPolicy: OnFailure
          volumes:
            - name: ddclient
              persistentVolumeClaim:
                claimName: ddclient