- hosts: all
  become: yes
  tasks:
    - name: Remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none
    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0
    - name: Add an apt signing key for Kubernetes
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
    - name: Adding apt repository for Kubernetes
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes.list
    - name: Install Kubernetes binaries
      apt: 
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - kubelet 
          - kubeadm 
          - kubectl
    - name: Hold versions for kubelet
      dpkg_selections:
        name: kubelet
        selection: hold
    - name: Hold versions for kubeadm
      dpkg_selections:
        name: kubeadm
        selection: hold
    - name: Hold versions for kubectl
      dpkg_selections:
        name: kubectl
        selection: hold
    - name: Add netbridge config ip6
      lineinfile:
        path: /etc/modules-load.d/k8s.conf
        line: 'br_netfilter'
        state: present
        create: yes
    - name: Add netbridge config ip6
      lineinfile:
        path: /etc/sysctl.d/k8s.conf
        line: 'net.bridge.bridge-nf-call-ip6tables = 1'
        state: present
        create: yes
    - name: Add netbridge config ip4
      lineinfile:
        path: /etc/sysctl.d/k8s.conf
        line: 'net.bridge.bridge-nf-call-iptables = 1'
        state: present
        create: yes
    - name: update sysctl
      command: sysctl --system
    - name: Restart kubelet
      service:
        name: kubelet
        daemon_reload: yes
        state: restarted
    - name: Add memory cgroup config to boot params
      replace:
        path: /boot/firmware/cmdline.txt
        regexp: '(fixrtc)$'
        replace: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1'