- hosts: all
  become: yes
  tasks:
    - name: Add memory cgroup config to boot params
      replace:
        path: /boot/firmware/cmdline.txt
        regexp: '(fixrtc)$'
        replace: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1'
    - name: Set a hostname
      hostname:
        # always unique
        name: node-{{ ansible_eth0.ipv4.address | replace('.','-') }}
        # easier to type hostname but not guaranteed to be unique
        # name: node{{ ansible_eth0.ipv4.address.split('.')[3][-1] }}
        # a little longer hostname, probably unique in most circumstances
        # name: node{{ ansible_eth0.ipv4.address.split('.')[3] }}
    - name: Unconditionally reboot the machine
      reboot:
        reboot_timeout: 3600