- hosts: all
  become: yes
  tasks:
  - name: Uninstall old versions of docker
    apt:
      name: ['docker', 'docker-engine', 'docker.io', 'containerd', 'runc']
      state: absent
      autoremove: yes
      purge: yes
  - name: Update all packages to their latest version
    apt:
      name: "*"
      state: latest
      update_cache: yes
  - name: Unconditionally reboot the machine
    reboot:
      reboot_timeout: 3600