apiVersion: v1
kind: PersistentVolume
metadata:
  name: ddclient
spec:
  capacity:
    storage: 10Mi
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.50
    path: /volume1/ddclient
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ddclient
spec:
  volumeName: ddclient
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddclient
  labels:
    app: ddclient
spec:
  selector:
    matchLabels:
      app: ddclient
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ddclient
    spec:
      volumes:
        - name: ddclient
          persistentVolumeClaim:
            claimName: ddclient
      containers:
        - name: ddclient
          image: linuxserver/ddclient
          imagePullPolicy: Always
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 200m
          env:
            - name: PUID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: "America/Los_Angeles"
          volumeMounts:
            - name: ddclient
              mountPath: /config