- hosts: all
  become: yes
  tasks:
  - name: Uninstall old versions of docker
    apt:
      name: ['docker', 'docker-engine', 'docker.io', 'containerd', 'runc']
      state: absent
      autoremove: yes
      purge: yes
  - name: Update all packages to their latest version
    apt:
      name: "*"
      state: latest
      update_cache: yes
  - name: Check if a reboot is required
    shell: "[ -f /var/run/reboot-required ]"
    failed_when: False
    register: reboot_required
    changed_when: reboot_required.rc == 0
    notify: Reboot

  handlers:
    - name: Reboot
      reboot:
        reboot_timeout: 3600