apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.50
    path: /volume1/minecraft
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft
spec:
  volumeName: minecraft
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: default
spec:
    ports:
    - name: minecraft
      port: 25565
      protocol: TCP
      targetPort: 25565
    selector:
      app: minecraft
    type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  selector:
    matchLabels:
      app: minecraft
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      volumes:
        - name: minecraft
          persistentVolumeClaim:
            claimName: minecraft
      containers:
        - name: minecraft
          image: itzg/minecraft-server:multiarch
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          ports:
            - name: minecraft
              containerPort: 25565
              protocol: TCP
          env:
            - name: VERSION
              value: "1.16.4"
            - name: EULA
              value: "TRUE"
            - name: WORLD
              value: "http://nas/mc-resources/Witchcraft%20and%20Wizardry.zip"
            - name: ENABLE_AUTOPAUSE
              value: "TRUE"
            - name: WHITELIST
              value: "Mateus80,Ada2015"
          volumeMounts:
            - name: minecraft
              mountPath: /data